#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    links:
       - redis:redis
    user: "1001:1002" #system dependent
   #  command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    command: bash -c "pip3 install -r requirements.txt && python /code/mysite/manage.py migrate && python /code/mysite/manage.py runserver 0.0.0.0:8000"

  nginx:
    restart: always
    build: ./nginx
    depends_on:
       - web
    ports:
       - 80:80
    links:
       - web:web

  redis:
    image: redis
    expose:
       - 6379



